# Generated by Django 5.1.5 on 2025-02-05 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_mgr', '0002_task_mgr_task'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='task_mgr_task',
            options={'ordering': ['starts_on'], 'verbose_name': 'Task', 'verbose_name_plural': 'Tasks'},
        ),
        migrations.AlterField(
            model_name='task_mgr_task',
            name='ends_on',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='task_mgr_task',
            name='starts_on',
            field=models.DateTimeField(),
        ),
    ]
